package:
  name: nanoimagingpack
  version: 2.0.0.dev4

source:
  git_rev: 
  git_url: https://gitlab.com/bionanoimaging/nanoimagingpack

requirements:
  build:
    - numpy>=1.12
    - python
    - setuptools
    - tifffile
    - scipy 
    - imageio
    - matplotlib
    - IPython
    - scikit-tensor-py3
    - python-bioformats
  run:
    - numpy>=1.12
    #- python
    - tifffile
    #- mock>=2.0
    - scipy
    - imageio
    - matplotlib
    - scikit-tensor-py3
    - python-bioformats
    #- IPython
test:
  imports:
    - NanoImagingPack

about:
  home: https://gitlab.com/bionanoimaging/nanoimagingpack
  license: GPL
  
